apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simple-webapp
  namespace: simple-webapp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`staging-api.fondsfinanz.de`) && PathPrefix(`/simple-webapp`)
      kind: Rule
      services:
        - name: simple-webapp
          port: 80
      middlewares:
        - name: stripprefix

